#!/usr/bin/env php
<?php

$pages = include __DIR__ . '/pages.php';

foreach ($pages as $page) {
  $file = $page['cacheFile'];
  $moniker = $page['moniker'];
  $url = $page['url'];
  if ( file_exists($file) ) {
    echo "SKIPPING: $moniker (already cached)";
  }
  else {
    echo "FETCHING: $moniker";
    if (isset(parse_url($url)['scheme'])) { // URL is remote
      system("curl '$url' > '$file'");
    }
    else { // URL is local
      copy($url, $file);
    }
  }
  echo PHP_EOL;
}

echo "DONE" . PHP_EOL;
